import React, {useRef, useState} from 'react';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import data from '@site/src/data/funds-2026-preview.json';
import styles from './FundsLeadMagnet.module.css';

/**
 * Email gate for the full "new VC funds 2026" list, embedded in the blog post
 * blog/2026-09-30-new-vc-funds-2026.md. It shows masked rows; on signup the
 * existing `newsletter-subscribe` edge function (with `magnet`) adds the email
 * to the magnet's Resend Segment, sends the newsletter welcome email, notifies
 * hq@ and returns the download links.
 * Data is generated by DVOS/raisetalks/smm/valley-20day/assets/funds-2026/research/build_outputs.py.
 */

const BRAND_GRADIENT = 'linear-gradient(75.88deg, #003687 -3.42%, #0077FF 99.98%)';
const MAGNET = 'new-vc-funds-2026';

type Downloads = {xlsx: string; csv: string};

export default function FundsLeadMagnet() {
  const {siteConfig} = useDocusaurusContext();
  const [email, setEmail] = useState('');
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [files, setFiles] = useState<Downloads | null>(null);
  const formLoadedAt = useRef(Date.now());
  const honeypotRef = useRef('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setStatus('loading');

    // Local preview only: the edge function is not running on localhost.
    if (['localhost', '127.0.0.1'].includes(window.location.hostname)) {
      await new Promise((r) => setTimeout(r, 600));
      setFiles({
        xlsx: '/downloads/nvf26-k7q3x9/raisetalks-new-vc-funds-2026.xlsx',
        csv: '/downloads/nvf26-k7q3x9/raisetalks-new-vc-funds-2026.csv',
      });
      setStatus('success');
      return;
    }

    try {
      const SUPABASE_URL = siteConfig.customFields?.SUPABASE_URL as string;
      const SUPABASE_ANON_KEY = siteConfig.customFields?.SUPABASE_ANON_KEY as string;
      const response = await fetch(`${SUPABASE_URL}/functions/v1/newsletter-subscribe`, {
        method: 'POST',
        headers: {'Content-Type': 'application/json', Authorization: `Bearer ${SUPABASE_ANON_KEY}`},
        body: JSON.stringify({
          email: email.trim(),
          magnet: MAGNET,
          website: honeypotRef.current,
          _formLoadedAt: formLoadedAt.current,
        }),
      });
      const body = await response.json();
      if (!response.ok || !body.files) throw new Error(body.error || 'Failed');
      setFiles(body.files);
      setStatus('success');
    } catch (error) {
      console.error('Lead magnet signup failed:', error);
      setStatus('error');
    }
  };

  return (
    <div className={styles.wrap} id="full-list">
      <div className={styles.table} aria-hidden="true">
        <div className={styles.thead}>
          <span>Fund</span>
          <span>Industry</span>
          <span className={styles.wide}>Region</span>
          <span className={styles.wide}>Stage</span>
        </div>
        {data.locked.slice(0, 9).map((r, i) => (
          <div key={i} className={styles.trow}>
            <span className={styles.mask} style={{width: `${55 + ((i * 37) % 40)}%`}} />
            <span>{r.primary}</span>
            <span className={styles.wide}>{r.region}</span>
            <span className={styles.wide}>{r.stage}</span>
          </div>
        ))}
      </div>

      <div className={styles.gate}>
        <div className={styles.card}>
          {status === 'success' && files ? (
            <>
              <p className={styles.title}>The full list is yours.</p>
              <p className={styles.sub}>Save the files now. You are also on the RaiseTalks mailing list.</p>
              <div className={styles.buttons}>
                <a href={files.xlsx} download className={styles.primary} style={{background: BRAND_GRADIENT}}>
                  Download Excel
                </a>
                <a href={files.csv} download className={styles.secondary}>
                  Download CSV
                </a>
              </div>
            </>
          ) : (
            <form onSubmit={handleSubmit} className={styles.form}>
              <p className={styles.title}>Get all {data.total} funds</p>
              <p className={styles.sub}>Excel and CSV with stage, first cheque, thesis and source for every fund.</p>
              {/* Honeypot field - invisible to real users, catches bots */}
              <input
                type="text"
                name="website"
                aria-hidden="true"
                tabIndex={-1}
                autoComplete="off"
                style={{position: 'absolute', left: '-9999px'}}
                onChange={(e) => {
                  honeypotRef.current = e.target.value;
                }}
              />
              <div className={styles.row}>
                <input
                  type="email"
                  required
                  placeholder="Your work email"
                  aria-label="Email address"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  disabled={status === 'loading'}
                  className={styles.input}
                />
                <button
                  type="submit"
                  disabled={status === 'loading'}
                  className={styles.primary}
                  style={{background: BRAND_GRADIENT}}>
                  {status === 'loading' ? 'Sending...' : 'Send me the list'}
                </button>
              </div>
              <p className={styles.note}>
                Free. Download straight away, and join the RaiseTalks mailing list with our weekly email of
                actively deploying funds. Unsubscribe anytime.
              </p>
              {status === 'error' && <p className={styles.error}>Something went wrong. Please try again.</p>}
            </form>
          )}
        </div>
      </div>
    </div>
  );
}
